#!/bin/bash

# seek-scaling wrapper
# Calls the test and graphing scripts
#
# Greg Smith greg@2ndQuadrant.com

# TODO Make these into input parameters
DESCR="Seek test"
FILENAME="seek-results.log"
GRAPH="results.png"
TESTDIR=`pwd`

BIN=`pwd`
pushd $TESTDIR
echo "# ${DESCR}" > ${FILENAME}
$BIN/seek-scaling-sysbench 2>&1 >>${FILENAME}
popd
mv ${TESTDIR}/${FILENAME} .

./seek-scaling-report ${FILENAME}
mv graph.png ${GRAPH}

