#!/bin/bash -x

#
# Execute sysbench seek test from the current working directory
#
# Greg Smith greg@2ndQuadrant.com
#
# Takes 1 input parameter: the base directory if your sysbench build
# tree.  If not supplied, it guesses you have a bzr checkout of version
# 0.4 in your home directory and tries there.
#

# TODO Make all of these proper command line parameters
THREADS="1 2 4 8 12 16 24 32 48 96"
GBSIZE=100
# If you name this "SECONDS" instead, sysbench changes it as the program runs; don't do that!
SECS=300
MODE=rndrd

#
# Cache flushing code only works as root
#
if [ ! "$USER" = "root" ] ; then
  echo Error:  the cache clearing code of seek-scaling can only be run as root.
  exit 1
fi

#
# Find sysbench executable
#
SYSBENCHBIN=`which sysbench`
if [ $? -ne 0 ] ; then
  SYSBENCHBIN=$HOME/0.4/sysbench/sysbench
  if [ ! -x $SYSBENCHBIN ] ; then
    echo Cannot find a sysbench binary to use.
    echo Place a binary in the PATH, or install a repo checkout to \$HOME/0.4
    exit 2
  fi
fi

$SYSBENCHBIN --test=fileio --num-threads=1 --file-num=$GBSIZE --file-total-size=${GBSIZE}G --file-block-size=8K --file-test-mode=rndrd --file-fsync-freq=0 --file-fsync-end=no prepare

for THREAD in $THREADS ; do
  # Try to clean the OS cache, will only work if run as root
  sync
  echo 3 > /proc/sys/vm/drop_caches

  $SYSBENCHBIN --test=fileio --num-threads=$THREAD --file-num=$GBSIZE --file-total-size=${GBSIZE}G --file-block-size=8K --file-test-mode=$MODE --file-fsync-freq=0 --file-fsync-end=no run --max-time=$SECS --max-requests=0
done

echo
echo == Test finished ==
echo
echo To cleanup:
echo
echo $SYSBENCHBIN --test=fileio --num-threads=1 --file-num=$GBSIZE --file-total-size=${GBSIZE}G --file-block-size=8K --file-test-mode=$MODE --file-fsync-freq=0 --file-fsync-end=no cleanup

