#!/bin/bash -x

#
# Execute sysbench seek test from the current working directory
#
# Greg Smith gsmith@gregsmith.com
#
# Takes 1 input parameter: the base directory if your sysbench build
# tree.  If not supplied, it guesses you have a bzr checkout of version
# 0.4 in home directory and tries there.
#

# TODO Make all of these proper command line parameters
THREADS="1 2 4 8 12 16 24 32 48 96"
GBSIZE=100
# If you name this "SECONDS" instead, sysbench changes it as the program runs; don't do that!
SECS=300
MODE=rndrd

PREFIX="$HOME/0.4"
if [ -n "$1" ] ; then
  PREFIX="$1"
fi
SYSBENCH=$PREFIX/sysbench/sysbench
if [ ! -x $SYSBENCH ] ; then
  echo Did not find a sysbench binary at $SYSBENCH
  exit 1
fi

$SYSBENCH --test=fileio --num-threads=1 --file-num=$GBSIZE --file-total-size=${GBSIZE}G --file-block-size=8K --file-test-mode=rndrd --file-fsync-freq=0 --file-fsync-end=no prepare

for THREAD in $THREADS ; do
  # Try to clean the OS cache, will only work if run as root
  sync
  echo 3 > /proc/sys/vm/drop_caches

  $SYSBENCH --test=fileio --num-threads=$THREAD --file-num=$GBSIZE --file-total-size=${GBSIZE}G --file-block-size=8K --file-test-mode=$MODE --file-fsync-freq=0 --file-fsync-end=no run --max-time=$SECS --max-requests=0
done

echo
echo == Test finished ==
echo
echo To cleanup:
echo
echo $SYSBENCH --test=fileio --num-threads=1 --file-num=$GBSIZE --file-total-size=${GBSIZE}G --file-block-size=8K --file-test-mode=$MODE --file-fsync-freq=0 --file-fsync-end=no cleanup

